# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{tfxl/CA_projects/tree/main/terminal_app}" }

# gem "rails"

gem 'json', '~> 2.5'
gem 'rainbow', '~> 3.0'
gem 'tty-cursor', '~> 0.7.1'
gem 'tty-markdown', '~> 0.7.0'
gem 'tty-prompt', '~> 0.23.1'
gem 'tty-screen', '~> 0.8.1'
gem "tty-progressbar", "~> 0.18.2"
